openapi: 3.0.0
info:
  title: Ruqqus
  version: '1.0'
  description: 'The initial version of the Ruqqus API, in support of user-authorized Applications.'
  termsOfService: 'https://ruqqus.com/help/terms'
  contact:
    url: 'https://ruqqus.com/help/contact'
    name: Ruqqus
  license:
    name: Mozilla Public License 2.0
    url: 'https://github.com/ruqqus/ruqqus/blob/master/LICENSE'
servers:
  - url: 'https://ruqqus.com/api/v1'
paths:
  '/board_available/{name}':
    get:
      summary: Guild Name Available
      tags: []
      operationId: get-board_available-name
      description: Checks if the guild name is availabile (not an existing guild)
      security:
        - OAuth2:
            - read
        - Access Token: []
  '/guild/{name}/listing':
    get:
      summary: Guild Post Listing
      tags: []
      operationId: get-api-v1-guild-name-listing
      description: ''
      security:
        - OAuth2:
            - read
        - Access Token: []
  '/mod/take/{pid}':
    post:
      summary: Yank Post
      operationId: post-mod-take-pid
      description: |
        Endpoint for yanking posts
      security:
        - OAuth2:
            - guildmaster
        - Access Token: []
  '/guild/{boardname}/comments':
    get:
      summary: Guild Comment Listing
      tags: []
      operationId: get-guild-boardname-comments
      description: Endpoint for retriving comments from a guild
      security:
        - OAuth2:
            - read
        - Access Token: []
  '/comment/{c_id}':
    get:
      summary: Comment JSON
      tags: []
      operationId: get-comment-c_id
      description: Get comment by ID
      security:
        - OAuth2:
            - read
        - Access Token: []
  /comment:
    post:
      summary: Submit a comment
      operationId: postcomment
      security:
        - OAuth2:
            - create
        - Access Token: []
      description: |-
        Post a comment under a post or another comment<br>
        In `parrent_fullname` prepend `t2_` to post id if commenting on a post, and prepend `t3_` to parent comment id if replying to a comment.
  '/delete/comment/{cid}':
    post:
      summary: Delete comment
      operationId: post-delete-comment-cid
      description: Delete a comment by ID
      security:
        - OAuth2:
            - delete
        - Access Token: []
  /front/listing:
    get:
      summary: Frontpage
      tags: []
      operationId: get-front-listing
      security:
        - OAuth2:
            - read
        - Access Token: []
      description: Ruqqus frontpage
  /all/listing:
    get:
      summary: All page
      tags: []
      operationId: get-all-listing
      security:
        - OAuth2:
            - read
        - Access Token: []
  /guilds:
    get:
      summary: Browse guilds
      tags: []
      operationId: get-guilds
      security:
        - OAuth2:
            - read
        - Access Token: []
  /front/comments:
    get:
      summary: Get comments
      tags: []
      operationId: get-front-comments
      security:
        - OAuth2:
            - read
        - Access Token: []
      description: Get all sitewide comments
  /identity:
    get:
      summary: Identity
      tags: []
      operationId: get-identity
      description: Get access token account data
      security:
        - OAuth2:
            - identity
        - Access Token: []
  '/post/{base36id}':
    get:
      summary: Post JSON
      tags: []
      operationId: get-post-base36id
      description: Get post data by ID
      security:
        - OAuth2:
            - read
        - Access Token: []
  /submit:
    post:
      summary: Submit a post
      operationId: post-submit
      security:
        - OAuth2:
            - create
        - Access Token: []
      description: Sumbit a post
  '/delete_post/{pid}':
    post:
      summary: ''
      operationId: post-delete_post-pid
      description: Delete a post
      security:
        - OAuth2:
            - delete
        - Access Token: []
  '/toggle_post_nsfl/{pid}':
    post:
      summary: Toggle post NSFL
      operationId: post-toggle_post_nsfl-pid
      security:
        - OAuth2:
            - update
        - Access Token: []
      description: Toggle NSFL on a post
  '/toggle_post_nsfw/{pid}':
    post:
      summary: ''
      operationId: post-toggle_post_nsfw-pid
      description: Toggle NSFW on a post
      security:
        - OAuth2:
            - update
        - Access Token: []
  '/is_available/{name}':
    get:
      summary: Username available
      tags: []
      operationId: get-is_available-name
      security:
        - OAuth2:
            - read
        - Access Token: []
      description: Check if username is available
  '/user/by_id/{uid}':
    get:
      summary: Get user by ID
      tags: []
      operationId: get-user-by_id-uid
      description: Get user by ID
      security:
        - OAuth2:
            - read
        - Access Token: []
  '/user/{username}/listing':
    get:
      summary: Users posts
      tags: []
      operationId: get-user-username-listing
      security:
        - OAuth2:
            - read
        - Access Token: []
  '/user/{username}/comments':
    get:
      summary: Get users comments
      tags: []
      operationId: get-user-username-comments
      description: Get comments for a specific user
      security:
        - OAuth2:
            - read
        - Access Token: []
  /saved:
    get:
      summary: Saved posts
      tags: []
      operationId: get-saved
      security:
        - OAuth2:
            - read
        - Access Token: []
      description: Get the list of your saved posts
  '/vote/post/{post_id}/{x}':
    post:
      summary: Vote on a post
      tags: []
      operationId: post-vote-post-post_id-x
      description: Cast vote on a post
      security:
        - OAuth2:
            - vote
        - Access Token: []
  '/vote/comment/{comment_id}/{x}':
    post:
      summary: Vote on a comment
      tags: []
      operationId: post-vote-comment-comment_id-x
      description: Cast vote on a comment
      security:
        - OAuth2:
            - vote
        - Access Token: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          scopes:
            identity: Allows the application to access the user's information
            create: Allows the application to submit items through the user
            read: Allows the application to request information about site objects
            update: Allows the application to update already-created submissions
            delete: Allows the application to delete submissions created by the user
            vote: Allows the application to vote on submissions through the user
            guildmaster: Allows the application to perform guildmaster actions through the user
      description: |
        OAuth2 flow for obtaining API application keys
    Access Token:
      type: apiKey
      in: header
      name: Authorization
      description: |
        Bearer: Token for accessing `/api/v1` endpoints
security:
  - OAuth2: []
  - Access Token: []
